language: java
jdk: 
  - oraclejdk8
before_install:
  - sudo sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get install python-software-properties
  - sudo apt-get install g++-5 gcc-5 gcc-5-multilib g++-5-multilib lib32stdc++6-5-dbg libstdc++6-5-dbg
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 80 --slave /usr/bin/g++ g++ /usr/bin/g++-5
  - wget http://services.gradle.org/distributions/gradle-3.1-bin.zip
  - unzip gradle-3.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-3.1
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v
